name: Publish new mattplottslib package to PyPI

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user 

    - name: Install tomli
      run: pip install tomli tomli-w
    - name: Bump patch version in pyproject.toml
      run: python3 "./bump_version.py"
    - name: Clean previous builds
      run: rm -rf dist/ build/ *.egg-info

    - name: Build new distribution
      run: python -m build
    - name: Upload distribution
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: >-
      Publish new mattplottslib package to PyPI
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: release
      url: https://pypi.org/project/mattplottslib/

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish mattplottslib distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://upload.pypi.org/legacy/

  publish-to-testpypi:
    name: Publish new mattplottslib package to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: release
      url: https://test.pypi.org/project/mattplottslib/

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish mattplottslib distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/